### ISSUE TITLE
RPC/RDMA v2 should support generic host authentication

### ISSUE THREAD

**Issue by chucklever** [chucklever/i-d-rpcrdma-version-two#2]
Tom Talpey suggested we wanted to use chained Sends instead of RDMA for large authentication payloads, and that we need to support generic authentication mechanisms that require multiple round trips.

**Comment by dnoveck** [comment]
There are two separate issues mentioned here. We should look at each one to see if it is essential, highly desirable, or nice to have.

**Comment by chucklever** [comment]
The host authentication mechanisms we are already familiar with (eg. ones that are built into TLS) can generate multiple challenges and responses (multiple round trips) and some of them may convey chains of trust that are considerably longer than our inline threshold. The latter issue is what might require Send chaining, if we feel that using RDMA_NOMSG is undesirable or unworkable for a host authentication mechanism.

**Comment by chucklever** [comment]
dnoveck says:
> I believe we will have trouble with a milestone more than a year from now. I find the prospect of a 10/20 or 11/20 milestone kind of frightening but am willing to go along if you think it is doable.

Independent of the other process obstacles, I think a 9/20 milestone is achievable.

> If it isn’t doable, we will need an alternative. One thing I have been thinking about is a change in the contents of the certificate property (the one wrapped in a pseudo opaque). I think we could support it being a union with two arms:
* An inline opaque certificate.
* A read chunk that tells the receiver were to obtain the certificate.

My original proposal for dealing with large certificates was to use RDMA. The problem with that is that the mechanism has to work both ways: client-to-server and server-to-client. The client has no way to predict how large the server's certification material is to set up a Reply chunk.

We could perhaps make that size a transport property so that the server can tell the client "yes, I have certificate material, and it's 9KB in size". That way the client can send its certificate material (possibly via RDMA) and provide a 9KB Reply chunk at the same time.

**Comment by chucklever** [comment]
The latest revision of rpcrdma-version-two includes support for the exchange of potentially large authentication material.
