### ISSUE TITLE
Enhancements to credit accounting in RPC/RDMA v2

### ISSUE THREAD

**Issue by chucklever** [chucklever/i-d-rpcrdma-version-two#4]
To support messages that have no reply, and to support messages that are spread over multiple Receive buffers, the base RPC/RDMA v2 transport protocol will require additions to its credit accounting mechanism. Consider:
* An rdma_proc that grants credits but does not bear a payload. RDMA_NOMSG with no chunks, or a new rdma_proc could be used for this purpose
* Credits granted for each direction of message flow -- or, if you will, for each set of Receive resources -- on the connection.

**Comment by dnoveck** [comment]
With regard two these two issues:
 - the fact that two distinct issues are joined in this way creates difficulties resolving the issues.
  - the first issue should be non-controversial and so reflected in the next draft.
  - the motivation for the second is not very clear  
 Also, it is not clear how this proposed change is or is not related to proposed extensions such as send chaining.  We need to move to resolution of the question of send chaining pretty soon or else the issue set for this document will be hard to manage.

**Comment by chucklever** [comment]
> With regard two these two issues:
> 
> * the fact that two distinct issues are joined in this way creates difficulties resolving the issues.

Please elucidate.

> * the first issue should be non-controversial and so reflected in the next draft.

Good point: that is a very simple extension to the protocol. I will work on that.

> * the motivation for the second is not very clear

To you :-) I've written and presented extensively on this topic. To wit:

> Also, it is not clear how this proposed change is or is not related to proposed extensions such as send chaining.  We need to move to resolution of the question of send chaining pretty soon or else the issue set for this document will be hard to manage.

Send chaining will be simple to introduce once we have sorted out the transport's ability to handle asymmetric message exchange, which boils down to enhancing credit accounting so that one peer can respond with zero, one, or multiple Sends to a message from the other peer on the connection.

**Comment by chucklever** [comment]
The latest revision of rpcrdma-version-two includes provisions for asymmetric message exchange. The details are a little vague for the moment. Prototyping should enable us to clear up any ambiguities.
